### ISSUE TITLE
Link to projects with cards

### ISSUE THREAD

**Issue by AustinMorales09** [KiahP/kpPortfolio#1]
Your cards should have a link to your projects on github, you will use the same link from github pages to display each project. You can use an anchor tag inside of the cards and set the href to your github links.

**Comment by KiahP** [comment]
I updated this by putting anchor tags around card-title and adding the github links to the href. 
<a href="https://kiahp.github.io/aboutMe/"> <h2 class="card-title">About Me</h2></a>
<a href="https://kiahp.github.io/madLibs/"><h2 class="card-title">Mad Libs</h2></a>
<a href="https://kiahp.github.io/productLanding/">  <h2 class="card-title">Product Landing</h2></a>
